config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'
  get 'restaurants/index'
  get 'restaurants/show'
  get 'restaurants/new'
  get 'restaurants/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants, only: %I[index show new create] do
    resources :reviews, only: %I[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates_associated :reviews
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: %w[chinese italian japanese french belgian] }
  validates :phone_number, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }
  validates_inclusion_of :rating, in: (0..5)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show]
  def index
    @restaurants = Restaurant.all
  end

  def show; end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %I[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="w-50 m-auto">
  <%= simple_form_for(@restaurant) do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :phone_number %>
      <%= f.input :category, collection: %w[chinese italian japanese french belgian] %>
      <%= f.submit %>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<h1 class="w-50 m-auto p-3 bg-primary text-white text-center">Yelp</h1>
<h3 class="w-50 m-auto mb-2 p-3 bg-primary text-white text-center">Find reviews and information about your favourite restuarants</h3>

<div class="w-50 m-auto mb-2 text-center">
  <%= link_to '<i class="fa-solid fa-square-plus fa-xl link-unstyled"></i> Add Restaurant'.html_safe, restaurants_new_path, style: 'text-decoration-none' %>
</div>
<% @restaurants.each do |restaurant| %>
  <%= link_to restaurant_path(restaurant), class: "text-decoration-none" do %>
    <div class="p-3 mb-2 w-50 m-auto border border-dark rounded">
      <h3 class="p-2 ms-2 mb-1 text-decoration-none"><%= restaurant.name %></h3>
      <h4 class="p-2 ms-2 mb-1"><%= restaurant.address %></h4>
      <h4 class="p-2 ms-2 mb-1"><%= restaurant.phone_number %></h4>
      <h4 class="p-2 ms-2 mb-1"><%= restaurant.category %></h4>
    </div>
  <% end %>
<% end %>

app/views/restaurants/new.html.erb
<h1 class="p-3 mb-2 w-50 m-auto text-center bg-primary text-white">Create a new Restaurant</h1>

<%= render partial: 'restaurants/form' %>

app/views/restaurants/show.html.erb
<h1 class="p-3 mb-2 w-50 m-auto text-center bg-primary text-white"><%= @restaurant.name  %></h1>

<div class="p-3 mb-2 w-50 m-auto border-bottom border-dark border-3">
  <h3 class="p-2 ms-2 mb-1"><%= @restaurant.address %></h3>
  <h3 class="p-2 ms-2 mb-1"><%= @restaurant.phone_number %></h3>
  <h3 class="p-2 ms-2 mb-1"><%= @restaurant.category %></h3>
</div>

<div class="w-50 m-auto mb-2 text-center">
  <%= link_to '<i class="fa-solid fa-square-plus fa-xl link-unstyled"></i> Add Review'.html_safe, new_restaurant_review_path(@restaurant), style: 'text-decoration-none' %>
</div>

<div class="w-50 m-auto text-center border border-dark p-3 mb-2">
  <% @restaurant.reviews.each do |review| %>
    <div class="mb-2" ><% (review.rating).to_i.times { %> <%= '⭐' %> <% } %>  </div>
    <div class="p-2 mb-2"><%= review.content %></div>
  <% end %>
</div>

<div class="w-50 m-auto text-center"><%= link_to 'Go back', { controller: 'restaurants', action: 'index'}, class: 'btn btn-primary ms-2' %></div>

app/views/reviews/_form.html.erb
<div class="w-50 m-auto">
  <%= simple_form_for [@restaurant, @review] do |f| %>
      <%= f.input :rating, as: :range, input_html:{ min:"1", max:"5" }%>
      <%= f.input :content %>
      <%= f.submit %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<h1 class="p-3 mb-2 w-50 m-auto text-center bg-primary text-white">Create a new review for <%= @restaurant.name %></h1>

<%= render partial: 'reviews/form' %>